name: simple-project

on:
  push:
    branches:
      - origin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Docker"
        uses: docker/setup-buildx-action@v2

      - name: "Pull Docker image and run container"
        run: |
          docker pull theoafactor/bitblog:123
          docker run -d -p 74:80 theoafactor/bitblog:123

